create table "users" ("id" serial primary key not null, "name" varchar(255) not null, "email" varchar(255) not null, "email_verified_at" timestamp(0) without time zone null, "password" varchar(255) not null, "remember_token" varchar(100) null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "users" add constraint "users_email_unique" unique ("email");
create table "password_resets" ("email" varchar(255) not null, "token" varchar(255) not null, "created_at" timestamp(0) without time zone null);
create index "password_resets_email_index" on "password_resets" ("email");
create table "destinies" ("id" serial primary key not null, "ciudad" varchar(60) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "origins" ("id" serial primary key not null, "ciudad" varchar(60) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "reservations" ("id" serial primary key not null, "monto" integer not null, "num_pasaporte" integer not null, "num_reserva_hotel" integer not null, "origin_id" integer not null, "destiny_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "reservations" add constraint "reservations_destiny_id_foreign" foreign key ("destiny_id") references "destinies" ("id");
alter table "reservations" add constraint "reservations_origin_id_foreign" foreign key ("origin_id") references "origins" ("id");
create table "airports" ("id" serial primary key not null, "ciudad" varchar(60) not null, "nombre" varchar(60) not null, "origin_id" integer not null, "destiny_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "airports" add constraint "airports_origin_id_foreign" foreign key ("origin_id") references "origins" ("id");
alter table "airports" add constraint "airports_destiny_id_foreign" foreign key ("destiny_id") references "destinies" ("id");
create table "socios" ("id" serial primary key not null, "numero" integer not null, "email" varchar(255) not null, "millas" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "flights" ("id" serial primary key not null, "fecha_ida" date not null, "capacidad" smallint not null, "num_pasajeros" smallint not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "administrators" ("id" serial primary key not null, "nombre" varchar(40) not null, "apellido" varchar(40) not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
 create table "tickets" ("id" serial primary key not null, "num_asiento" smallint not null, "hora" timestamp(0) without time zone not null, "origen" varchar(80) not null, "destino" varchar(80) not null, "doc_identificacion" varchar(40) not null, "tipo_pasajero" varchar(20) not null, "flight_id" integer not null, "reservation_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
 alter table "tickets" add constraint "tickets_flight_id_foreign" foreign key ("flight_id") references "flights" ("id");
 alter table "tickets" add constraint "tickets_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
create table "check_ins" ("id" serial primary key not null, "cuenta" integer not null, "num_vuelo" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "purchases" ("id" serial primary key not null, "fecha" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "stops" ("id" serial primary key not null, "nombre" varchar(60) not null, "flight_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "stops" add constraint "stops_flight_id_foreign" foreign key ("flight_id") references "flights" ("id");
create table "passengers" ("id" serial primary key not null, "nombre" varchar(255) not null, "apellido" varchar(255) not null, "num_asiento" integer not null, "flight_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "passengers" add constraint "passengers_flight_id_foreign" foreign key ("flight_id") references "flights" ("id");
create table "packages" ("id" serial primary key not null, "descuento" integer not null, "fecha_vencimiento" timestamp(0) without time zone not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "reservation-packages" ("package_id" integer not null, "reservation_id" integer not null);
alter table "reservation-packages" add constraint "reservation_packages_package_id_foreign" foreign key ("package_id") references "packages" ("id");
alter table "reservation-packages" add constraint "reservation_packages_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
create table "cars" ("id" serial primary key not null, "patente" varchar(255) not null, "marca" varchar(255) not null, "modelo" varchar(255) not null, "capacidad" decimal(8, 2) not null, "package_id" integer not null, "reservation_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "cars" add constraint "cars_package_id_foreign" foreign key ("package_id") references "packages" ("id");
alter table "cars" add constraint "cars_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
create table "reservation_users" ("id" serial primary key not null, "reservation_id" integer not null, "user_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "reservation_users" add constraint "reservation_users_user_id_foreign" foreign key ("user_id") references "users" ("id");
alter table "reservation_users" add constraint "reservation_users_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
create table "hotels" ("id" serial primary key not null, "ciudad" varchar(255) not null, "nombre" varchar(255) not null, "clase" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
create table "rooms" ("id" serial primary key not null, "numero" integer not null, "hotel_id" integer not null, "capacidad" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "rooms" add constraint "rooms_hotel_id_foreign" foreign key ("hotel_id") references "hotels" ("id");
create table "hotel_reservations" ("id" serial primary key not null, "cantidad_personas" decimal(8, 2) not null, "room_id" integer not null, "package_id" integer not null, "reservation_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "hotel_reservations" add constraint "hotel_reservations_room_id_foreign" foreign key ("room_id") references "rooms" ("id");
alter table "hotel_reservations" add constraint "hotel_reservations_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
alter table "hotel_reservations" add constraint "hotel_reservations_package_id_foreign" foreign key ("package_id") references "packages" ("id");
create table "flightpackages" ("flight_id" integer not null, "package_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "flightpackages" add constraint "flightpackages_flight_id_foreign" foreign key ("flight_id") references "flights" ("id");
alter table "flightpackages" add constraint "flightpackages_package_id_foreign" foreign key ("package_id") references "packages" ("id");
create table "stopflights" ("stop_id" integer not null, "flight_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "stopflights" add constraint "stopflights_flight_id_foreign" foreign key ("flight_id") references "flights" ("id");
alter table "stopflights" add constraint "stopflights_stop_id_foreign" foreign key ("stop_id") references "stops" ("id");
create table "administratorpackages" ("administrator_id" integer not null, "package_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "administratorpackages" add constraint "administratorpackages_package_id_foreign" foreign key ("package_id") references "packages" ("id");
alter table "administratorpackages" add constraint "administratorpackages_administrator_id_foreign" foreign key ("administrator_id") references "administrators" ("id");
create table "reservationflights" ("reservation_id" integer not null, "flight_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "reservationflights" add constraint "reservationflights_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
alter table "reservationflights" add constraint "reservationflights_flight_id_foreign" foreign key ("flight_id") references "flights" ("id");
create table "reservationadministrators" ("reservation_id" integer not null, "administrator_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "reservationadministrators" add constraint "reservationadministrators_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
alter table "reservationadministrators" add constraint "reservationadministrators_administrator_id_foreign" foreign key ("administrator_id") references "administrators" ("id");
create table "clientreservations" ("user_id" integer not null, "reservation_id" integer not null, "created_at" timestamp(0) without time zone null, "updated_at" timestamp(0) without time zone null);
alter table "clientreservations" add constraint "clientreservations_user_id_foreign" foreign key ("user_id") references "users" ("id");
alter table "clientreservations" add constraint "clientreservations_reservation_id_foreign" foreign key ("reservation_id") references "reservations" ("id");
create table "hotel_reservation-packages" ("package_id" integer not null, "hotel_reservations_id" integer not null);
alter table "hotel_reservation-packages" add constraint "hotel_reservation_packages_package_id_foreign" foreign key ("package_id") references "packages" ("id");
alter table "hotel_reservation-packages" add constraint "hotel_reservation_packages_hotel_reservations_id_foreign" foreign key ("hotel_reservations_id") references "hotel_reservations" ("id");
